//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlech.SshAgentLibTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dlech.SshAgentLibTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsa_1 {
            get {
                object obj = ResourceManager.GetObject("dsa_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsa_1_cert_fp {
            get {
                object obj = ResourceManager.GetObject("dsa_1_cert_fp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsa_1_cert_pub {
            get {
                object obj = ResourceManager.GetObject("dsa_1_cert_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsa_1_fp {
            get {
                object obj = ResourceManager.GetObject("dsa_1_fp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsa_1_fp_bb {
            get {
                object obj = ResourceManager.GetObject("dsa_1_fp_bb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsa_1_param_g {
            get {
                object obj = ResourceManager.GetObject("dsa_1_param_g", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsa_1_param_priv {
            get {
                object obj = ResourceManager.GetObject("dsa_1_param_priv", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsa_1_param_pub {
            get {
                object obj = ResourceManager.GetObject("dsa_1_param_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsa_1_pub {
            get {
                object obj = ResourceManager.GetObject("dsa_1_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsa_1_pw {
            get {
                object obj = ResourceManager.GetObject("dsa_1_pw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsa_2 {
            get {
                object obj = ResourceManager.GetObject("dsa_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsa_2_fp {
            get {
                object obj = ResourceManager.GetObject("dsa_2_fp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsa_2_fp_bb {
            get {
                object obj = ResourceManager.GetObject("dsa_2_fp_bb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsa_2_pub {
            get {
                object obj = ResourceManager.GetObject("dsa_2_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsa_n {
            get {
                object obj = ResourceManager.GetObject("dsa_n", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsa_n_pw {
            get {
                object obj = ResourceManager.GetObject("dsa_n_pw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsa_no_passphrase {
            get {
                object obj = ResourceManager.GetObject("dsa_no_passphrase", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsa_no_passphrase_pub {
            get {
                object obj = ResourceManager.GetObject("dsa_no_passphrase_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsa_with_passphrase {
            get {
                object obj = ResourceManager.GetObject("dsa_with_passphrase", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsa_with_passphrase_pub {
            get {
                object obj = ResourceManager.GetObject("dsa_with_passphrase_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_1 {
            get {
                object obj = ResourceManager.GetObject("ecdsa_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_1_cert_fp {
            get {
                object obj = ResourceManager.GetObject("ecdsa_1_cert_fp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_1_cert_pub {
            get {
                object obj = ResourceManager.GetObject("ecdsa_1_cert_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_1_fp {
            get {
                object obj = ResourceManager.GetObject("ecdsa_1_fp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_1_fp_bb {
            get {
                object obj = ResourceManager.GetObject("ecdsa_1_fp_bb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_1_param_curve {
            get {
                object obj = ResourceManager.GetObject("ecdsa_1_param_curve", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_1_param_priv {
            get {
                object obj = ResourceManager.GetObject("ecdsa_1_param_priv", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_1_param_pub {
            get {
                object obj = ResourceManager.GetObject("ecdsa_1_param_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_1_pub {
            get {
                object obj = ResourceManager.GetObject("ecdsa_1_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_1_pw {
            get {
                object obj = ResourceManager.GetObject("ecdsa_1_pw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_2 {
            get {
                object obj = ResourceManager.GetObject("ecdsa_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_2_fp {
            get {
                object obj = ResourceManager.GetObject("ecdsa_2_fp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_2_fp_bb {
            get {
                object obj = ResourceManager.GetObject("ecdsa_2_fp_bb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_2_param_curve {
            get {
                object obj = ResourceManager.GetObject("ecdsa_2_param_curve", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_2_param_priv {
            get {
                object obj = ResourceManager.GetObject("ecdsa_2_param_priv", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_2_param_pub {
            get {
                object obj = ResourceManager.GetObject("ecdsa_2_param_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_2_pub {
            get {
                object obj = ResourceManager.GetObject("ecdsa_2_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_n {
            get {
                object obj = ResourceManager.GetObject("ecdsa_n", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_n_pw {
            get {
                object obj = ResourceManager.GetObject("ecdsa_n_pw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_no_passphrase {
            get {
                object obj = ResourceManager.GetObject("ecdsa_no_passphrase", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_no_passphrase_pub {
            get {
                object obj = ResourceManager.GetObject("ecdsa_no_passphrase_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_with_passphrase {
            get {
                object obj = ResourceManager.GetObject("ecdsa_with_passphrase", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ecdsa_with_passphrase_pub {
            get {
                object obj = ResourceManager.GetObject("ecdsa_with_passphrase_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ed25519_1 {
            get {
                object obj = ResourceManager.GetObject("ed25519_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ed25519_1_cert_fp {
            get {
                object obj = ResourceManager.GetObject("ed25519_1_cert_fp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ed25519_1_cert_pub {
            get {
                object obj = ResourceManager.GetObject("ed25519_1_cert_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ed25519_1_fp {
            get {
                object obj = ResourceManager.GetObject("ed25519_1_fp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ed25519_1_fp_bb {
            get {
                object obj = ResourceManager.GetObject("ed25519_1_fp_bb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ed25519_1_pub {
            get {
                object obj = ResourceManager.GetObject("ed25519_1_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ed25519_1_pw {
            get {
                object obj = ResourceManager.GetObject("ed25519_1_pw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ed25519_2 {
            get {
                object obj = ResourceManager.GetObject("ed25519_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ed25519_2_fp {
            get {
                object obj = ResourceManager.GetObject("ed25519_2_fp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ed25519_2_fp_bb {
            get {
                object obj = ResourceManager.GetObject("ed25519_2_fp_bb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ed25519_2_pub {
            get {
                object obj = ResourceManager.GetObject("ed25519_2_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] emptyFile_ppk {
            get {
                object obj = ResourceManager.GetObject("emptyFile_ppk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] non_standard_length_ppk {
            get {
                object obj = ResourceManager.GetObject("non_standard_length_ppk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pw {
            get {
                object obj = ResourceManager.GetObject("pw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_1 {
            get {
                object obj = ResourceManager.GetObject("rsa_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_1_cert_fp {
            get {
                object obj = ResourceManager.GetObject("rsa_1_cert_fp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_1_cert_pub {
            get {
                object obj = ResourceManager.GetObject("rsa_1_cert_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_1_fp_bb {
            get {
                object obj = ResourceManager.GetObject("rsa_1_fp_bb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_1_param_n {
            get {
                object obj = ResourceManager.GetObject("rsa_1_param_n", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_1_param_p {
            get {
                object obj = ResourceManager.GetObject("rsa_1_param_p", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_1_param_q {
            get {
                object obj = ResourceManager.GetObject("rsa_1_param_q", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_1_pw {
            get {
                object obj = ResourceManager.GetObject("rsa_1_pw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_11_fp {
            get {
                object obj = ResourceManager.GetObject("rsa_11_fp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_12_pub {
            get {
                object obj = ResourceManager.GetObject("rsa_12_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_2 {
            get {
                object obj = ResourceManager.GetObject("rsa_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_2_fp_bb {
            get {
                object obj = ResourceManager.GetObject("rsa_2_fp_bb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_2_param_n {
            get {
                object obj = ResourceManager.GetObject("rsa_2_param_n", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_2_param_p {
            get {
                object obj = ResourceManager.GetObject("rsa_2_param_p", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_2_param_q {
            get {
                object obj = ResourceManager.GetObject("rsa_2_param_q", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_21_fp {
            get {
                object obj = ResourceManager.GetObject("rsa_21_fp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_22_pub {
            get {
                object obj = ResourceManager.GetObject("rsa_22_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_n {
            get {
                object obj = ResourceManager.GetObject("rsa_n", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_n_pw {
            get {
                object obj = ResourceManager.GetObject("rsa_n_pw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_no_passphrase {
            get {
                object obj = ResourceManager.GetObject("rsa_no_passphrase", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_no_passphrase_pub {
            get {
                object obj = ResourceManager.GetObject("rsa_no_passphrase_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_with_passphrase {
            get {
                object obj = ResourceManager.GetObject("rsa_with_passphrase", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa_with_passphrase_pub {
            get {
                object obj = ResourceManager.GetObject("rsa_with_passphrase_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa1_1 {
            get {
                object obj = ResourceManager.GetObject("rsa1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa1_1_fp {
            get {
                object obj = ResourceManager.GetObject("rsa1_1_fp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa1_1_fp_bb {
            get {
                object obj = ResourceManager.GetObject("rsa1_1_fp_bb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa1_1_param_n {
            get {
                object obj = ResourceManager.GetObject("rsa1_1_param_n", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa1_1_pub {
            get {
                object obj = ResourceManager.GetObject("rsa1_1_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa1_1_pw {
            get {
                object obj = ResourceManager.GetObject("rsa1_1_pw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa1_2 {
            get {
                object obj = ResourceManager.GetObject("rsa1_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa1_2_fp {
            get {
                object obj = ResourceManager.GetObject("rsa1_2_fp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa1_2_fp_bb {
            get {
                object obj = ResourceManager.GetObject("rsa1_2_fp_bb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa1_2_param_n {
            get {
                object obj = ResourceManager.GetObject("rsa1_2_param_n", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsa1_2_pub {
            get {
                object obj = ResourceManager.GetObject("rsa1_2_pub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ssh1_rsa_no_passphrase_ppk {
            get {
                object obj = ResourceManager.GetObject("ssh1_rsa_no_passphrase_ppk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ssh1_rsa_ppk {
            get {
                object obj = ResourceManager.GetObject("ssh1_rsa_ppk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ssh2_dsa_no_passphrase_ppk {
            get {
                object obj = ResourceManager.GetObject("ssh2_dsa_no_passphrase_ppk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ssh2_dsa_ppk {
            get {
                object obj = ResourceManager.GetObject("ssh2_dsa_ppk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ssh2_rsa_no_passphrase_ppk {
            get {
                object obj = ResourceManager.GetObject("ssh2_rsa_no_passphrase_ppk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ssh2_rsa_non_ascii_passphrase_ppk {
            get {
                object obj = ResourceManager.GetObject("ssh2_rsa_non_ascii_passphrase_ppk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ssh2_rsa_ppk {
            get {
                object obj = ResourceManager.GetObject("ssh2_rsa_ppk", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
