
// This file has been generated by the GUI designer. Do not modify.

public partial class KeyManagerWindow
{
	private global::SshAgentLib.GTK.KeyManagerWiget keymanagerwiget1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget KeyManagerWindow
		this.Name = "KeyManagerWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("SSH Key Manager");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.Gravity = ((global::Gdk.Gravity)(5));
		// Container child KeyManagerWindow.Gtk.Container+ContainerChild
		this.keymanagerwiget1 = new global::SshAgentLib.GTK.KeyManagerWiget ();
		this.keymanagerwiget1.Events = ((global::Gdk.EventMask)(256));
		this.keymanagerwiget1.Name = "keymanagerwiget1";
		this.Add (this.keymanagerwiget1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 723;
		this.DefaultHeight = 257;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
