
// This file has been generated by the GUI designer. Do not modify.
namespace SshAgentLib.GTK
{
	public partial class KeyManagerWiget
	{
		private global::Gtk.Table mMainLayoutTable;
		private global::Gtk.Label label1;
		private global::Gtk.HButtonBox mButtonBox;
		private global::Gtk.Button mLockButton;
		private global::Gtk.Button mUnlockButton;
		private global::Gtk.Button mAddButton;
		private global::Gtk.Button mRemoveButton;
		private global::Gtk.Button mRemoveAllButton;
		private global::Gtk.Button mRefreshButton;
		private global::Gtk.ScrolledWindow mGtkScrolledWindow;
		private global::Gtk.NodeView mKeyNodeView;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SshAgentLib.GTK.KeyManagerWiget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "SshAgentLib.GTK.KeyManagerWiget";
			// Container child SshAgentLib.GTK.KeyManagerWiget.Gtk.Container+ContainerChild
			this.mMainLayoutTable = new global::Gtk.Table (((uint)(2)), ((uint)(1)), false);
			this.mMainLayoutTable.Name = "mMainLayoutTable";
			this.mMainLayoutTable.RowSpacing = ((uint)(6));
			this.mMainLayoutTable.ColumnSpacing = ((uint)(6));
			// Container child mMainLayoutTable.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Message");
			this.mMainLayoutTable.Add (this.label1);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.mMainLayoutTable [this.label1]));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child mMainLayoutTable.Gtk.Table+TableChild
			this.mButtonBox = new global::Gtk.HButtonBox ();
			this.mButtonBox.Name = "mButtonBox";
			this.mButtonBox.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child mButtonBox.Gtk.ButtonBox+ButtonBoxChild
			this.mLockButton = new global::Gtk.Button ();
			this.mLockButton.CanFocus = true;
			this.mLockButton.Name = "mLockButton";
			this.mLockButton.UseUnderline = true;
			this.mLockButton.Label = global::Mono.Unix.Catalog.GetString ("Lock");
			this.mButtonBox.Add (this.mLockButton);
			global::Gtk.ButtonBox.ButtonBoxChild w2 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.mButtonBox [this.mLockButton]));
			w2.Expand = false;
			w2.Fill = false;
			// Container child mButtonBox.Gtk.ButtonBox+ButtonBoxChild
			this.mUnlockButton = new global::Gtk.Button ();
			this.mUnlockButton.CanFocus = true;
			this.mUnlockButton.Name = "mUnlockButton";
			this.mUnlockButton.UseUnderline = true;
			this.mUnlockButton.Label = global::Mono.Unix.Catalog.GetString ("Unlock");
			this.mButtonBox.Add (this.mUnlockButton);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.mButtonBox [this.mUnlockButton]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child mButtonBox.Gtk.ButtonBox+ButtonBoxChild
			this.mAddButton = new global::Gtk.Button ();
			this.mAddButton.CanFocus = true;
			this.mAddButton.Name = "mAddButton";
			this.mAddButton.UseUnderline = true;
			this.mAddButton.Label = global::Mono.Unix.Catalog.GetString ("Add...");
			this.mButtonBox.Add (this.mAddButton);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.mButtonBox [this.mAddButton]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child mButtonBox.Gtk.ButtonBox+ButtonBoxChild
			this.mRemoveButton = new global::Gtk.Button ();
			this.mRemoveButton.CanFocus = true;
			this.mRemoveButton.Name = "mRemoveButton";
			this.mRemoveButton.UseUnderline = true;
			this.mRemoveButton.Label = global::Mono.Unix.Catalog.GetString ("Remove");
			this.mButtonBox.Add (this.mRemoveButton);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.mButtonBox [this.mRemoveButton]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Container child mButtonBox.Gtk.ButtonBox+ButtonBoxChild
			this.mRemoveAllButton = new global::Gtk.Button ();
			this.mRemoveAllButton.CanFocus = true;
			this.mRemoveAllButton.Name = "mRemoveAllButton";
			this.mRemoveAllButton.UseUnderline = true;
			this.mRemoveAllButton.Label = global::Mono.Unix.Catalog.GetString ("Remove All");
			this.mButtonBox.Add (this.mRemoveAllButton);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.mButtonBox [this.mRemoveAllButton]));
			w6.Position = 4;
			w6.Expand = false;
			w6.Fill = false;
			// Container child mButtonBox.Gtk.ButtonBox+ButtonBoxChild
			this.mRefreshButton = new global::Gtk.Button ();
			this.mRefreshButton.CanFocus = true;
			this.mRefreshButton.Name = "mRefreshButton";
			this.mRefreshButton.UseUnderline = true;
			this.mRefreshButton.Label = global::Mono.Unix.Catalog.GetString ("Refresh");
			this.mButtonBox.Add (this.mRefreshButton);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.mButtonBox [this.mRefreshButton]));
			w7.Position = 5;
			w7.Expand = false;
			w7.Fill = false;
			this.mMainLayoutTable.Add (this.mButtonBox);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.mMainLayoutTable [this.mButtonBox]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child mMainLayoutTable.Gtk.Table+TableChild
			this.mGtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.mGtkScrolledWindow.Name = "mGtkScrolledWindow";
			this.mGtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child mGtkScrolledWindow.Gtk.Container+ContainerChild
			this.mKeyNodeView = new global::Gtk.NodeView ();
			this.mKeyNodeView.CanFocus = true;
			this.mKeyNodeView.Name = "mKeyNodeView";
			this.mGtkScrolledWindow.Add (this.mKeyNodeView);
			this.mMainLayoutTable.Add (this.mGtkScrolledWindow);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.mMainLayoutTable [this.mGtkScrolledWindow]));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.mMainLayoutTable);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.mLockButton.Clicked += new global::System.EventHandler (this.OnMLockButtonClicked);
			this.mUnlockButton.Clicked += new global::System.EventHandler (this.OnMUnlockButtonClicked);
			this.mAddButton.Clicked += new global::System.EventHandler (this.OnMAddButtonClicked);
			this.mRemoveButton.Clicked += new global::System.EventHandler (this.OnMRemoveButtonClicked);
			this.mRemoveAllButton.Clicked += new global::System.EventHandler (this.OnMRemoveAllButtonClicked);
			this.mRefreshButton.Clicked += new global::System.EventHandler (this.OnMRefreshButtonClicked);
		}
	}
}
